### ISSUE TITLE
Errors in kubernetes/linux doc

### ISSUE THREAD

**Issue by saschanockel** [UnitedPlanet/intrexx-cloud-playbooks#11]
Just some minor errors in the [Container Setup section](https://github.com/UnitedPlanet/intrexx-cloud-playbooks/blob/master/kubernetes/linux/docs/README.md#container-setup)
- the URL  for the 21.03 tar download should be https://download.unitedplanet.com/intrexx/100000/intrexx-21.03-linux-x86_64.tar.gz
- The tar command should be `tar -zxvf intrexx-21.03-linux-x86_64.tar.gz`
- The folder name of the extracted folder is `IX_21.03-OU0`, at least when I downloaded it

**Comment by manr** [comment]
Thank you for reporting this.
